#!/usr/bin/env python3
"""Cap OMP's working context window for ~1M-token models.

OMP compacts at contextWindow minus a 15% reserve, so a 1M model only compacts near 850K,
well past where long-context quality drops. A global compaction.thresholdTokens cannot be
used instead: OMP clamps it only to contextWindow - 1, so smaller-window models (swe-2 at
262K, Codex gpt-6 at 272K) would compact too late and overflow.

This rewrites ~/.omp/agent/models.yml with a modelOverrides.contextWindow for every cached
model of the listed providers whose window is >= 900K. Re-run after `omp` discovers new
models. The generated file is owned by this script; put other models.yml content in
EXTRA below rather than editing the output.
"""

import json
import os
import sqlite3
import sys

CAP = int(sys.argv[1]) if len(sys.argv) > 1 else 320_000
MIN_WINDOW = 900_000
PROVIDERS = {
    "anthropic",
    "commandcode",
    "devin",
    "google-antigravity",
    "kimi-code",
    "openai-codex",
    "xai-oauth",
}
EXTRA = ""

home = os.path.expanduser("~/.omp/agent")
db = sqlite3.connect(f"file:{home}/models.db?mode=ro", uri=True)

overrides: dict[str, set[str]] = {}
for provider_id, models in db.execute("SELECT provider_id, models FROM model_cache"):
    provider = provider_id.split(":")[0]
    if provider not in PROVIDERS:
        continue
    for model in json.loads(models):
        if (model.get("contextWindow") or 0) >= MIN_WINDOW:
            overrides.setdefault(provider, set()).add(model["id"])

lines = [
    "# Generated by dotfile/omp/cap-context.py; re-run it instead of editing.",
    f"# Caps ~1M-context models at {CAP} tokens so compaction runs around {int(CAP * 0.85)}.",
    "providers:",
]
for provider in sorted(overrides):
    lines.append(f"  {provider}:")
    lines.append("    modelOverrides:")
    for model_id in sorted(overrides[provider]):
        lines.append(f"      {json.dumps(model_id)}:")
        lines.append(f"        contextWindow: {CAP}")

with open(f"{home}/models.yml", "w") as f:
    f.write("\n".join(lines) + "\n" + EXTRA)

total = sum(len(v) for v in overrides.values())
print(f"capped {total} models across {len(overrides)} providers at {CAP}")
